### ISSUE TITLE
Rebuild containers containing visual studio to fix a compiler bug

### ISSUE THREAD

**Issue by anarazel** [cirruslabs/docker-images-windows#23]
Hi,

For postgres CI we're hitting a code generation bug with visual studio. The bug is present in visual studio 16.9.3 and fixed at least in 16.11.1, but possibly earlier. Could you rebuild the containers so that a new version is included? The fixed version is available via chocolatey, so a simple rebuild should do:
https://community.chocolatey.org/packages/visualstudio2019buildtools#versionhistory

It'd be great if you could afterwards also trigger a rebuild for https://github.com/cirruslabs/vm-images/blob/master/googlecompute/windows_images.json - if the images aren't cached on the VM, it takes much longer to start jobs...

Regards,

Andres

**Comment by anarazel** [comment]
@fkorotkov Ping. Unfortunately the bug (which turns out to be a ucrt bug, not VS directly, but a newer msvc pulls in a newer ucrt) forced us to install msvc on our own. I was able to slim down the docker layer size quite a bit by only including the absolutely necessary parts for us (see https://github.com/anarazel/postgres/blob/ci/ci/docker/windows_vs_2019#L80), but it's still slowing down instance start times noticeably. Presumably due to not being pre-pulled to the host.

**Comment by ericoporto** [comment]
@anarazel did your in-place update of VS2022 worked?

**Comment by anarazel** [comment]
@ericoporto it did, but we ended up moving away from windows containers - they're just too slow.
